/* I'm editing this, you can't stop me dad */
#include <stdint.h>

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Entities_FingerScannerWindowsJNI */

#ifndef _Included_Entities_FingerScannerWindowsJNI
#define _Included_Entities_FingerScannerWindowsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Entities_FingerScannerWindowsJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Entities_FingerScannerWindowsJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
